### ISSUE TITLE
git status ment

### ISSUE THREAD

**Issue by shcrela** [HadrienG2/ddhc#37]
Hadrien,

Tu peux nous expliquer pourquoi quand je fait git status, il dit que ma branche est à jour avec upstream, mais quand je fais un pull, il se trouve qu'il y a eu pas mal de changements.

Merci.

**Comment by HadrienG2** [comment]
`git status` ne fait pas d'échanges réseau, il s'exprime seulement par rapport à la dernière version des branches qui a été téléchargée depuis la remote correspondante.
